version: '3'

services:
  base:
    container_name: pg_monitor_base
    build: .
    volumes:
      - /www/pg_monitor/prometheus/conf/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
  postgres_exporter:
    image: wrouesnel/postgres_exporter
    container_name: pg_monitor_exporter
    ports:
      - 3001:9187
    environment:
      - PG_EXPORTER_EXTEND_QUERY_PATH=/pg_exporter/query/
    volumes:
      - /www/pg_monitor/pg_exporter/query/:/pg_exporter/query/
    env_file:
      - .env
    restart: unless-stopped
  prometheus:
    image: bitnami/prometheus:latest
    container_name: pg_monitor_prometheus
    volumes:
      - /www/pg_monitor/prometheus/data:/opt/bitnami/prometheus/data
      - /www/pg_monitor/prometheus/conf/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    depends_on:
      - postgres_exporter
      - base
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: pg_monitor_grafana
    volumes:
      - /www/pg_monitor/grafana/data:/var/lib/grafana
      - /www/pg_monitor/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    restart: unless-stopped
