version: '3'

services:
  postgres_exporter:
    image: wrouesnel/postgres_exporter
    container_name: pg_monitor_exporter
    env_file:
      - .env
  prometheus:
    image: bitnami/prometheus:latest
    container_name: pg_monitor_prometheus
    volumes:
      - /www/pg_monitor/prometheus/data:/opt/bitnami/prometheus/data
      - /www/pg_monitor/prometheus/conf/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    depends_on:
      - postgres_exporter
  grafana:
    image: grafana/grafana
    container_name: pg_monitor_grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
